"""Key every company-scoped table by its company.

PostgreSQL will not partition a table unless every unique constraint contains the
partition key, the primary key included — and every one of these tables was keyed
by `id` alone. Spec 181 FR-005 asks for tables that *can* be partitioned by
company, and this is the change that makes them so: the key becomes
`(tenant_id, id)`, in that order, which is also the better index in a system where
every read names a company.

A foreign key in PostgreSQL binds to an index rather than to columns, so the old
key cannot simply be replaced underneath one. Every reference that pointed at
`id` alone is therefore dropped and made again over `(tenant_id, parent_id)` —
106 of them. That is not merely the cost of the change, it is most of
its value: a row can no longer name a parent belonging to another company, and the
database is what refuses it. Four tests existed only to prove the readers caught
such rows; they now prove the schema will not hold them.

`security_audit_event` is deliberately left alone. A signup, an admission and a
failed login happen before there is a company, and that is where they are written,
so its company column is nullable and cannot be part of a key.

The foreign-key index rule moves with it (`index_foreign_keys`): it indexes the
whole key rather than its first column, because the first column is now the
company on every one of these. Asking only about the first column would have found
`tenant_id` already indexed and quietly left 190 references unindexed —
`business_event.causation_id` among them, the one that took a company deletion from
thirty-six minutes to under four seconds.

Revision ID: 0088_tenant_scoped_keys
Revises: 0087_cost_conversion
"""

from alembic import op

revision = "0088_tenant_scoped_keys"
down_revision = "0087_cost_conversion"
branch_labels = None
depends_on = None

#: The tables whose key becomes `(tenant_id, id)`.
SCOPED: tuple[str, ...] = (
    "accounting_target",
    "accounting_target_reference",
    "action",
    "analysis_request",
    "analytics_report",
    "business_event",
    "chat_message",
    "chat_session",
    "commitment",
    "commitment_hold",
    "commitment_revision",
    "company_invitation",
    "component_assignment_part",
    "component_assignment_revision",
    "cost_attribution_part",
    "cost_attribution_revision",
    "cost_captured_basis",
    "cost_captured_contribution_basis",
    "cost_captured_inventory_basis",
    "cost_commercial_direct_part",
    "cost_commercial_inventory_part",
    "cost_commercial_match_revision",
    "cost_company_census",
    "cost_company_census_document",
    "cost_company_census_line",
    "cost_company_census_movement",
    "cost_company_census_source",
    "cost_company_contribution_input",
    "cost_company_contribution_result",
    "cost_company_generation",
    "cost_company_inventory_input",
    "cost_company_inventory_result",
    "cost_company_manifest",
    "cost_company_publication",
    "cost_component_basis",
    "cost_component_replacement",
    "cost_contribution_generation",
    "cost_contribution_review",
    "cost_contribution_row",
    "cost_contribution_snapshot",
    "cost_conversion_basis_revision",
    "cost_correction_basis",
    "cost_generation",
    "cost_input_manifest",
    "cost_inventory_generation",
    "cost_inventory_member",
    "cost_inventory_ownership_part",
    "cost_inventory_publication",
    "cost_inventory_review",
    "cost_inventory_row",
    "cost_inventory_snapshot",
    "cost_manifest_attribution",
    "cost_manifest_component",
    "cost_manifest_correction",
    "cost_manifest_receipt",
    "cost_manifest_replacement",
    "cost_movement_basis",
    "cost_opening_basis",
    "cost_ownership_revision",
    "cost_policy_revision",
    "cost_publication",
    "cost_receipt_basis",
    "cost_revenue_match_basis",
    "cost_scope_review",
    "cost_scope_review_category",
    "cost_selling_attribution_part",
    "cost_selling_review_category",
    "cost_selling_review_member",
    "cost_valuation_assessment_part",
    "cost_valuation_assessment_revision",
    "demo_data_connection",
    "document",
    "document_line",
    "fact",
    "finance_reference",
    "finance_role_destination",
    "finance_state",
    "finance_target_mapping_revision",
    "financial_component",
    "handling_unit",
    "import_job",
    "interpretation_outcome",
    "interpretation_record_reference",
    "interpretation_rule",
    "invitation_delivery",
    "item",
    "ledger_entry",
    "ledger_reversal",
    "location",
    "lot",
    "mcp_access_token",
    "movement",
    "movement_correction",
    "opening_item_detail",
    "opening_scope",
    "ordinary_company_creation",
    "party",
    "party_group",
    "party_group_member",
    "party_group_price_list",
    "party_hold",
    "party_price_list",
    "party_role",
    "payment_term",
    "playground_run",
    "playground_step",
    "price_list",
    "price_list_entry",
    "projection_checkpoint",
    "projection_row",
    "reality_gap",
    "reality_gap_entry",
    "reservation",
    "return_announcement",
    "rule_interpretation_outcome",
    "scheduled_job",
    "scheduled_job_run",
    "secret",
    "secret_audit_event",
    "serial_unit",
    "settlement_allocation",
    "shipment",
    "shipment_event",
    "shipment_event_supersession",
    "shipment_package",
    "source_artifact",
    "source_capability",
    "source_classification_mapping_revision",
    "source_record",
    "source_stream",
    "source_system",
    "storyline_trace_entry",
    "subledger_account",
    "tenant_membership",
)

#: Every reference that has to be dropped before a key can move, as
#: (table, columns, target table, the name it was given in the models, ondelete).
#: It is dropped by the name PostgreSQL actually has, read from the catalog rather
#: than assumed, because a database migrated for years may not spell it the way a
#: fresh one would; the recorded name is what the downgrade puts back, because
#: later revisions drop some of these by name and would not find them otherwise.
DROPPED: tuple[tuple[str, tuple[str, ...], str, str, str], ...] = (
    (
        "ai_settings",
        ("api_key_secret_id",),
        "secret",
        "fk_ai_settings_api_key_secret_id_secret",
        "",
    ),
    (
        "analysis_request",
        ("run_id",),
        "scheduled_job_run",
        "analysis_request_run_id_fkey",
        "",
    ),
    ("business_event", ("action_id",), "action", "business_event_action_id_fkey", ""),
    (
        "business_event",
        ("causation_id",),
        "business_event",
        "business_event_causation_id_fkey",
        "",
    ),
    (
        "business_event",
        ("source_record_id",),
        "source_record",
        "business_event_source_record_id_fkey",
        "",
    ),
    (
        "chat_message",
        ("session_id",),
        "chat_session",
        "chat_message_session_id_fkey",
        "",
    ),
    ("commitment", ("document_id",), "document", "commitment_document_id_fkey", ""),
    (
        "commitment",
        ("document_line_id",),
        "document_line",
        "commitment_document_line_id_fkey",
        "",
    ),
    ("commitment", ("from_party_id",), "party", "commitment_from_party_id_fkey", ""),
    ("commitment", ("item_id",), "item", "commitment_item_id_fkey", ""),
    ("commitment", ("location_id",), "location", "commitment_location_id_fkey", ""),
    ("commitment", ("to_party_id",), "party", "commitment_to_party_id_fkey", ""),
    (
        "commitment_hold",
        ("commitment_id",),
        "commitment",
        "commitment_hold_commitment_id_fkey",
        "",
    ),
    (
        "commitment_revision",
        ("commitment_id",),
        "commitment",
        "commitment_revision_commitment_id_fkey",
        "",
    ),
    (
        "commitment_revision",
        ("source_record_id",),
        "source_record",
        "commitment_revision_source_record_id_fkey",
        "",
    ),
    ("document", ("party_id",), "party", "document_party_id_fkey", ""),
    ("document", ("payment_term_id",), "payment_term", "fk_document_payment_term", ""),
    ("document", ("ship_to_party_id",), "party", "document_ship_to_party_id_fkey", ""),
    (
        "document",
        ("source_record_id",),
        "source_record",
        "document_source_record_id_fkey",
        "",
    ),
    (
        "document_line",
        ("billed_document_line_id",),
        "document_line",
        "fk_document_line_billed_document_line",
        "",
    ),
    (
        "document_line",
        ("document_id",),
        "document",
        "document_line_document_id_fkey",
        "",
    ),
    ("document_line", ("item_id",), "item", "document_line_item_id_fkey", ""),
    (
        "document_line",
        ("price_list_entry_id",),
        "price_list_entry",
        "fk_document_line_price_entry",
        "",
    ),
    (
        "fact",
        ("interpretation_rule_id",),
        "interpretation_rule",
        "fact_interpretation_rule_id_fkey",
        "",
    ),
    ("fact", ("source_record_id",), "source_record", "fact_source_record_id_fkey", ""),
    (
        "finance_target_mapping_revision",
        ("action_id",),
        "action",
        "finance_target_mapping_revision_action_id_fkey",
        "",
    ),
    (
        "handling_unit",
        ("source_record_id",),
        "source_record",
        "handling_unit_source_record_id_fkey",
        "",
    ),
    (
        "import_job",
        ("source_record_id",),
        "source_record",
        "import_job_source_record_id_fkey",
        "",
    ),
    (
        "interpretation_outcome",
        ("import_job_id",),
        "import_job",
        "interpretation_outcome_import_job_id_fkey",
        "",
    ),
    (
        "interpretation_outcome",
        ("source_record_id",),
        "source_record",
        "interpretation_outcome_source_record_id_fkey",
        "",
    ),
    (
        "interpretation_record_reference",
        ("outcome_id",),
        "interpretation_outcome",
        "interpretation_record_reference_outcome_id_fkey",
        "CASCADE",
    ),
    (
        "interpretation_rule",
        ("gap_id",),
        "reality_gap",
        "interpretation_rule_gap_id_fkey",
        "",
    ),
    (
        "invitation_delivery",
        ("invitation_id",),
        "company_invitation",
        "invitation_delivery_invitation_id_fkey",
        "",
    ),
    ("item", ("default_location_id",), "location", "item_default_location_id_fkey", ""),
    ("item", ("source_record_id",), "source_record", "item_source_record_id_fkey", ""),
    ("ledger_entry", ("document_id",), "document", "ledger_entry_document_id_fkey", ""),
    ("ledger_entry", ("party_id",), "party", "ledger_entry_party_id_fkey", ""),
    (
        "ledger_entry",
        ("source_record_id",),
        "source_record",
        "ledger_entry_source_record_id_fkey",
        "",
    ),
    (
        "location",
        ("parent_location_id",),
        "location",
        "location_parent_location_id_fkey",
        "",
    ),
    (
        "location",
        ("source_record_id",),
        "source_record",
        "location_source_record_id_fkey",
        "",
    ),
    ("lot", ("item_id",), "item", "lot_item_id_fkey", ""),
    ("lot", ("source_record_id",), "source_record", "lot_source_record_id_fkey", ""),
    ("movement", ("commitment_id",), "commitment", "movement_commitment_id_fkey", ""),
    (
        "movement",
        ("from_location_id",),
        "location",
        "movement_from_location_id_fkey",
        "",
    ),
    (
        "movement",
        ("handling_unit_id",),
        "handling_unit",
        "fk_movement_handling_unit_id",
        "",
    ),
    ("movement", ("item_id",), "item", "movement_item_id_fkey", ""),
    ("movement", ("lot_id",), "lot", "fk_movement_lot_id", ""),
    (
        "movement",
        ("resolves_movement_id",),
        "movement",
        "fk_movement_resolves_movement",
        "",
    ),
    (
        "movement",
        ("return_announcement_id",),
        "return_announcement",
        "fk_movement_return_announcement",
        "",
    ),
    ("movement", ("serial_unit_id",), "serial_unit", "fk_movement_serial_unit_id", ""),
    (
        "movement",
        ("shipment_package_id",),
        "shipment_package",
        "fk_movement_shipment_package",
        "",
    ),
    (
        "movement",
        ("source_record_id",),
        "source_record",
        "movement_source_record_id_fkey",
        "",
    ),
    ("movement", ("to_location_id",), "location", "movement_to_location_id_fkey", ""),
    (
        "movement_correction",
        ("compensating_movement_id",),
        "movement",
        "movement_correction_compensating_movement_id_fkey",
        "",
    ),
    (
        "movement_correction",
        ("original_movement_id",),
        "movement",
        "movement_correction_original_movement_id_fkey",
        "",
    ),
    (
        "movement_correction",
        ("replacement_movement_id",),
        "movement",
        "movement_correction_replacement_movement_id_fkey",
        "",
    ),
    ("party", ("payment_term_id",), "payment_term", "fk_party_payment_term", ""),
    (
        "party",
        ("source_record_id",),
        "source_record",
        "party_source_record_id_fkey",
        "",
    ),
    (
        "party_group",
        ("source_record_id",),
        "source_record",
        "party_group_source_record_id_fkey",
        "",
    ),
    (
        "party_group_member",
        ("party_group_id",),
        "party_group",
        "party_group_member_party_group_id_fkey",
        "",
    ),
    (
        "party_group_member",
        ("party_id",),
        "party",
        "party_group_member_party_id_fkey",
        "",
    ),
    (
        "party_group_price_list",
        ("party_group_id",),
        "party_group",
        "party_group_price_list_party_group_id_fkey",
        "",
    ),
    (
        "party_group_price_list",
        ("price_list_id",),
        "price_list",
        "party_group_price_list_price_list_id_fkey",
        "",
    ),
    ("party_hold", ("party_id",), "party", "party_hold_party_id_fkey", ""),
    ("party_price_list", ("party_id",), "party", "party_price_list_party_id_fkey", ""),
    (
        "party_price_list",
        ("price_list_id",),
        "price_list",
        "party_price_list_price_list_id_fkey",
        "",
    ),
    (
        "party_role",
        ("default_location_id",),
        "location",
        "party_role_default_location_id_fkey",
        "",
    ),
    ("party_role", ("party_id",), "party", "party_role_party_id_fkey", ""),
    (
        "payment_term",
        ("source_record_id",),
        "source_record",
        "payment_term_source_record_id_fkey",
        "",
    ),
    (
        "price_list",
        ("source_record_id",),
        "source_record",
        "price_list_source_record_id_fkey",
        "",
    ),
    ("price_list_entry", ("item_id",), "item", "price_list_entry_item_id_fkey", ""),
    (
        "price_list_entry",
        ("price_list_id",),
        "price_list",
        "price_list_entry_price_list_id_fkey",
        "",
    ),
    (
        "price_list_entry",
        ("source_record_id",),
        "source_record",
        "price_list_entry_source_record_id_fkey",
        "",
    ),
    (
        "reality_gap_entry",
        ("gap_id",),
        "reality_gap",
        "reality_gap_entry_gap_id_fkey",
        "",
    ),
    (
        "reservation",
        ("commitment_id",),
        "commitment",
        "reservation_commitment_id_fkey",
        "",
    ),
    (
        "reservation",
        ("handling_unit_id",),
        "handling_unit",
        "fk_reservation_handling_unit_id",
        "",
    ),
    ("reservation", ("item_id",), "item", "reservation_item_id_fkey", ""),
    ("reservation", ("location_id",), "location", "reservation_location_id_fkey", ""),
    ("reservation", ("lot_id",), "lot", "fk_reservation_lot_id", ""),
    (
        "reservation",
        ("serial_unit_id",),
        "serial_unit",
        "fk_reservation_serial_unit_id",
        "",
    ),
    (
        "return_announcement",
        ("commitment_id",),
        "commitment",
        "return_announcement_commitment_id_fkey",
        "",
    ),
    (
        "return_announcement",
        ("source_record_id",),
        "source_record",
        "return_announcement_source_record_id_fkey",
        "",
    ),
    (
        "rule_interpretation_outcome",
        ("fact_id",),
        "fact",
        "rule_interpretation_outcome_fact_id_fkey",
        "",
    ),
    (
        "rule_interpretation_outcome",
        ("rule_id",),
        "interpretation_rule",
        "rule_interpretation_outcome_rule_id_fkey",
        "",
    ),
    (
        "rule_interpretation_outcome",
        ("source_record_id",),
        "source_record",
        "rule_interpretation_outcome_source_record_id_fkey",
        "",
    ),
    (
        "secret_audit_event",
        ("secret_id",),
        "secret",
        "secret_audit_event_secret_id_fkey",
        "",
    ),
    ("serial_unit", ("item_id",), "item", "serial_unit_item_id_fkey", ""),
    ("serial_unit", ("lot_id",), "lot", "serial_unit_lot_id_fkey", ""),
    (
        "serial_unit",
        ("source_record_id",),
        "source_record",
        "serial_unit_source_record_id_fkey",
        "",
    ),
    (
        "settlement_allocation",
        ("invoice_ledger_entry_id",),
        "ledger_entry",
        "settlement_allocation_invoice_ledger_entry_id_fkey",
        "",
    ),
    (
        "settlement_allocation",
        ("payment_ledger_entry_id",),
        "ledger_entry",
        "settlement_allocation_payment_ledger_entry_id_fkey",
        "",
    ),
    ("shipment", ("counterparty_id",), "party", "shipment_counterparty_id_fkey", ""),
    (
        "shipment",
        ("source_record_id",),
        "source_record",
        "shipment_source_record_id_fkey",
        "",
    ),
    (
        "shipment_event",
        ("shipment_id",),
        "shipment",
        "shipment_event_shipment_id_fkey",
        "",
    ),
    (
        "shipment_event",
        ("shipment_package_id",),
        "shipment_package",
        "shipment_event_shipment_package_id_fkey",
        "",
    ),
    (
        "shipment_event",
        ("source_record_id",),
        "source_record",
        "shipment_event_source_record_id_fkey",
        "",
    ),
    (
        "shipment_event_supersession",
        ("replacement_event_id",),
        "shipment_event",
        "shipment_event_supersession_replacement_event_id_fkey",
        "",
    ),
    (
        "shipment_event_supersession",
        ("source_record_id",),
        "source_record",
        "shipment_event_supersession_source_record_id_fkey",
        "",
    ),
    (
        "shipment_event_supersession",
        ("superseded_event_id",),
        "shipment_event",
        "shipment_event_supersession_superseded_event_id_fkey",
        "",
    ),
    (
        "shipment_package",
        ("shipment_id",),
        "shipment",
        "shipment_package_shipment_id_fkey",
        "",
    ),
    (
        "shipment_package",
        ("source_record_id",),
        "source_record",
        "shipment_package_source_record_id_fkey",
        "",
    ),
    (
        "source_capability",
        ("source_system_id",),
        "source_system",
        "source_capability_source_system_id_fkey",
        "",
    ),
    (
        "source_classification_mapping_revision",
        ("action_id",),
        "action",
        "source_classification_mapping_revision_action_id_fkey",
        "",
    ),
    (
        "source_record",
        ("source_artifact_id",),
        "source_artifact",
        "fk_source_record_source_artifact_id",
        "",
    ),
    (
        "source_record",
        ("supersedes_source_record_id",),
        "source_record",
        "fk_source_record_supersedes",
        "",
    ),
    (
        "source_stream",
        ("current_source_record_id",),
        "source_record",
        "source_stream_current_source_record_id_fkey",
        "",
    ),
)

#: Every reference as it is made again, carrying the company.
REFERENCES: tuple[tuple[str, tuple[str, ...], str, tuple[str, ...], str, str], ...] = (
    (
        "ai_settings",
        ("tenant_id", "api_key_secret_id"),
        "secret",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "analysis_request",
        ("tenant_id", "run_id"),
        "scheduled_job_run",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "business_event",
        ("tenant_id", "action_id"),
        "action",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "business_event",
        ("tenant_id", "causation_id"),
        "business_event",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "business_event",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "chat_message",
        ("tenant_id", "session_id"),
        "chat_session",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "commitment",
        ("tenant_id", "document_id"),
        "document",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "commitment",
        ("tenant_id", "document_line_id"),
        "document_line",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "commitment",
        ("tenant_id", "from_party_id"),
        "party",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("commitment", ("tenant_id", "item_id"), "item", ("tenant_id", "id"), "", ""),
    (
        "commitment",
        ("tenant_id", "location_id"),
        "location",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("commitment", ("tenant_id", "to_party_id"), "party", ("tenant_id", "id"), "", ""),
    (
        "commitment_hold",
        ("tenant_id", "commitment_id"),
        "commitment",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "commitment_revision",
        ("tenant_id", "commitment_id"),
        "commitment",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "commitment_revision",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("document", ("tenant_id", "party_id"), "party", ("tenant_id", "id"), "", ""),
    (
        "document",
        ("tenant_id", "payment_term_id"),
        "payment_term",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "document",
        ("tenant_id", "ship_to_party_id"),
        "party",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "document",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "document_line",
        ("tenant_id", "billed_document_line_id"),
        "document_line",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "document_line",
        ("tenant_id", "document_id"),
        "document",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("document_line", ("tenant_id", "item_id"), "item", ("tenant_id", "id"), "", ""),
    (
        "document_line",
        ("tenant_id", "price_list_entry_id"),
        "price_list_entry",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "fact",
        ("tenant_id", "interpretation_rule_id"),
        "interpretation_rule",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "fact",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "finance_target_mapping_revision",
        ("tenant_id", "action_id"),
        "action",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "handling_unit",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "import_job",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "interpretation_outcome",
        ("tenant_id", "import_job_id"),
        "import_job",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "interpretation_outcome",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "interpretation_record_reference",
        ("tenant_id", "outcome_id"),
        "interpretation_outcome",
        ("tenant_id", "id"),
        "CASCADE",
        "",
    ),
    (
        "interpretation_rule",
        ("tenant_id", "gap_id"),
        "reality_gap",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "invitation_delivery",
        ("tenant_id", "invitation_id"),
        "company_invitation",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "item",
        ("tenant_id", "default_location_id"),
        "location",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "item",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "ledger_entry",
        ("tenant_id", "document_id"),
        "document",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("ledger_entry", ("tenant_id", "party_id"), "party", ("tenant_id", "id"), "", ""),
    (
        "ledger_entry",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "location",
        ("tenant_id", "parent_location_id"),
        "location",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "location",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("lot", ("tenant_id", "item_id"), "item", ("tenant_id", "id"), "", ""),
    (
        "lot",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement",
        ("tenant_id", "commitment_id"),
        "commitment",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement",
        ("tenant_id", "from_location_id"),
        "location",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement",
        ("tenant_id", "handling_unit_id"),
        "handling_unit",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("movement", ("tenant_id", "item_id"), "item", ("tenant_id", "id"), "", ""),
    ("movement", ("tenant_id", "lot_id"), "lot", ("tenant_id", "id"), "", ""),
    (
        "movement",
        ("tenant_id", "resolves_movement_id"),
        "movement",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement",
        ("tenant_id", "return_announcement_id"),
        "return_announcement",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement",
        ("tenant_id", "serial_unit_id"),
        "serial_unit",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement",
        ("tenant_id", "shipment_package_id"),
        "shipment_package",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement",
        ("tenant_id", "to_location_id"),
        "location",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement_correction",
        ("tenant_id", "compensating_movement_id"),
        "movement",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement_correction",
        ("tenant_id", "original_movement_id"),
        "movement",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "movement_correction",
        ("tenant_id", "replacement_movement_id"),
        "movement",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party",
        ("tenant_id", "payment_term_id"),
        "payment_term",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party_group",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party_group_member",
        ("tenant_id", "party_group_id"),
        "party_group",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party_group_member",
        ("tenant_id", "party_id"),
        "party",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party_group_price_list",
        ("tenant_id", "party_group_id"),
        "party_group",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party_group_price_list",
        ("tenant_id", "price_list_id"),
        "price_list",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("party_hold", ("tenant_id", "party_id"), "party", ("tenant_id", "id"), "", ""),
    (
        "party_price_list",
        ("tenant_id", "party_id"),
        "party",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party_price_list",
        ("tenant_id", "price_list_id"),
        "price_list",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "party_role",
        ("tenant_id", "default_location_id"),
        "location",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("party_role", ("tenant_id", "party_id"), "party", ("tenant_id", "id"), "", ""),
    (
        "payment_term",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "price_list",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("price_list_entry", ("tenant_id", "item_id"), "item", ("tenant_id", "id"), "", ""),
    (
        "price_list_entry",
        ("tenant_id", "price_list_id"),
        "price_list",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "price_list_entry",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "reality_gap_entry",
        ("tenant_id", "gap_id"),
        "reality_gap",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "reservation",
        ("tenant_id", "commitment_id"),
        "commitment",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "reservation",
        ("tenant_id", "handling_unit_id"),
        "handling_unit",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("reservation", ("tenant_id", "item_id"), "item", ("tenant_id", "id"), "", ""),
    (
        "reservation",
        ("tenant_id", "location_id"),
        "location",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("reservation", ("tenant_id", "lot_id"), "lot", ("tenant_id", "id"), "", ""),
    (
        "reservation",
        ("tenant_id", "serial_unit_id"),
        "serial_unit",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "return_announcement",
        ("tenant_id", "commitment_id"),
        "commitment",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "return_announcement",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "rule_interpretation_outcome",
        ("tenant_id", "fact_id"),
        "fact",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "rule_interpretation_outcome",
        ("tenant_id", "rule_id"),
        "interpretation_rule",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "rule_interpretation_outcome",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "secret_audit_event",
        ("tenant_id", "secret_id"),
        "secret",
        ("tenant_id", "id"),
        "",
        "",
    ),
    ("serial_unit", ("tenant_id", "item_id"), "item", ("tenant_id", "id"), "", ""),
    ("serial_unit", ("tenant_id", "lot_id"), "lot", ("tenant_id", "id"), "", ""),
    (
        "serial_unit",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "settlement_allocation",
        ("tenant_id", "invoice_ledger_entry_id"),
        "ledger_entry",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "settlement_allocation",
        ("tenant_id", "payment_ledger_entry_id"),
        "ledger_entry",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment",
        ("tenant_id", "counterparty_id"),
        "party",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment_event",
        ("tenant_id", "shipment_id"),
        "shipment",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment_event",
        ("tenant_id", "shipment_package_id"),
        "shipment_package",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment_event",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment_event_supersession",
        ("tenant_id", "replacement_event_id"),
        "shipment_event",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment_event_supersession",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment_event_supersession",
        ("tenant_id", "superseded_event_id"),
        "shipment_event",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment_package",
        ("tenant_id", "shipment_id"),
        "shipment",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "shipment_package",
        ("tenant_id", "source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "source_capability",
        ("tenant_id", "source_system_id"),
        "source_system",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "source_classification_mapping_revision",
        ("tenant_id", "action_id"),
        "action",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "source_record",
        ("tenant_id", "source_artifact_id"),
        "source_artifact",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "source_record",
        ("tenant_id", "supersedes_source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
    (
        "source_stream",
        ("tenant_id", "current_source_record_id"),
        "source_record",
        ("tenant_id", "id"),
        "",
        "",
    ),
)

INDEX_DROPS: tuple[tuple[str, str, tuple[str, ...], bool], ...] = (
    ("ix_ai_settings_api_key_secret_id", "ai_settings", ("api_key_secret_id",), False),
    ("ix_analysis_request_run_id", "analysis_request", ("run_id",), False),
    ("ix_business_event_action_id", "business_event", ("action_id",), False),
    ("ix_business_event_causation_id", "business_event", ("causation_id",), False),
    (
        "ix_business_event_source_record_id",
        "business_event",
        ("source_record_id",),
        False,
    ),
    ("ix_chat_message_session_id", "chat_message", ("session_id",), False),
    ("ix_commitment_document_id", "commitment", ("document_id",), False),
    ("ix_commitment_document_line_id", "commitment", ("document_line_id",), False),
    ("ix_commitment_from_party_id", "commitment", ("from_party_id",), False),
    ("ix_commitment_item_id", "commitment", ("item_id",), False),
    ("ix_commitment_location_id", "commitment", ("location_id",), False),
    ("ix_commitment_to_party_id", "commitment", ("to_party_id",), False),
    ("ix_commitment_hold_commitment_id", "commitment_hold", ("commitment_id",), False),
    (
        "ix_commitment_revision_commitment_id",
        "commitment_revision",
        ("commitment_id",),
        False,
    ),
    (
        "ix_commitment_revision_source_record_id",
        "commitment_revision",
        ("source_record_id",),
        False,
    ),
    (
        "ix_cost_attribution_part_receipt_basis_id",
        "cost_attribution_part",
        ("receipt_basis_id",),
        False,
    ),
    (
        "ix_cost_attribution_part_tenant_id",
        "cost_attribution_part",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_attribution_revision_tenant_id",
        "cost_attribution_revision",
        ("tenant_id",),
        False,
    ),
    ("ix_cost_captured_basis_census_id", "cost_captured_basis", ("census_id",), False),
    ("ix_cost_captured_basis_tenant_id", "cost_captured_basis", ("tenant_id",), False),
    (
        "ix_cost_captured_contribution_basis_document_line_id",
        "cost_captured_contribution_basis",
        ("document_line_id",),
        False,
    ),
    (
        "ix_cost_captured_contribution_basis_review_id",
        "cost_captured_contribution_basis",
        ("review_id",),
        False,
    ),
    (
        "ix_cost_captured_contribution_basis_tenant_id",
        "cost_captured_contribution_basis",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_captured_inventory_basis_item_id",
        "cost_captured_inventory_basis",
        ("item_id",),
        False,
    ),
    (
        "ix_cost_captured_inventory_basis_review_id",
        "cost_captured_inventory_basis",
        ("review_id",),
        False,
    ),
    (
        "ix_cost_captured_inventory_basis_tenant_id",
        "cost_captured_inventory_basis",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_commercial_direct_part_tenant_id",
        "cost_commercial_direct_part",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_commercial_inventory_part_tenant_id",
        "cost_commercial_inventory_part",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_commercial_match_revision_tenant_id",
        "cost_commercial_match_revision",
        ("tenant_id",),
        False,
    ),
    ("ix_cost_company_census_tenant_id", "cost_company_census", ("tenant_id",), False),
    (
        "ix_cost_company_census_document_document_id",
        "cost_company_census_document",
        ("document_id",),
        False,
    ),
    (
        "ix_cost_company_census_document_tenant_id",
        "cost_company_census_document",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_census_line_document_line_id",
        "cost_company_census_line",
        ("document_line_id",),
        False,
    ),
    (
        "ix_cost_company_census_line_tenant_id",
        "cost_company_census_line",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_census_movement_movement_id",
        "cost_company_census_movement",
        ("movement_id",),
        False,
    ),
    (
        "ix_cost_company_census_movement_tenant_id",
        "cost_company_census_movement",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_census_source_interpretation_outcome_id",
        "cost_company_census_source",
        ("interpretation_outcome_id",),
        False,
    ),
    (
        "ix_cost_company_census_source_source_record_id",
        "cost_company_census_source",
        ("source_record_id",),
        False,
    ),
    (
        "ix_cost_company_census_source_tenant_id",
        "cost_company_census_source",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_contribution_input_census_line_id",
        "cost_company_contribution_input",
        ("census_line_id",),
        False,
    ),
    (
        "ix_cost_company_contribution_input_inventory_review_id",
        "cost_company_contribution_input",
        ("inventory_review_id",),
        False,
    ),
    (
        "ix_cost_company_contribution_input_review_id",
        "cost_company_contribution_input",
        ("review_id",),
        False,
    ),
    (
        "ix_cost_company_contribution_input_tenant_id",
        "cost_company_contribution_input",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_contribution_result_contribution_generation_id",
        "cost_company_contribution_result",
        ("contribution_generation_id",),
        False,
    ),
    (
        "ix_cost_company_contribution_result_contribution_input_id",
        "cost_company_contribution_result",
        ("contribution_input_id",),
        False,
    ),
    (
        "ix_cost_company_contribution_result_review_id",
        "cost_company_contribution_result",
        ("review_id",),
        False,
    ),
    (
        "ix_cost_company_contribution_result_tenant_id",
        "cost_company_contribution_result",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_generation_tenant_id",
        "cost_company_generation",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_inventory_input_item_id",
        "cost_company_inventory_input",
        ("item_id",),
        False,
    ),
    (
        "ix_cost_company_inventory_input_review_id",
        "cost_company_inventory_input",
        ("review_id",),
        False,
    ),
    (
        "ix_cost_company_inventory_input_tenant_id",
        "cost_company_inventory_input",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_inventory_result_inventory_generation_id",
        "cost_company_inventory_result",
        ("inventory_generation_id",),
        False,
    ),
    (
        "ix_cost_company_inventory_result_inventory_input_id",
        "cost_company_inventory_result",
        ("inventory_input_id",),
        False,
    ),
    (
        "ix_cost_company_inventory_result_tenant_id",
        "cost_company_inventory_result",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_manifest_census_id",
        "cost_company_manifest",
        ("census_id",),
        False,
    ),
    (
        "ix_cost_company_manifest_tenant_id",
        "cost_company_manifest",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_company_publication_tenant_id",
        "cost_company_publication",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_component_basis_tenant_id",
        "cost_component_basis",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_component_replacement_tenant_id",
        "cost_component_replacement",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_contribution_generation_tenant_id",
        "cost_contribution_generation",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_contribution_review_tenant_id",
        "cost_contribution_review",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_contribution_row_contribution_basis_member_id",
        "cost_contribution_row",
        ("contribution_basis_member_id",),
        False,
    ),
    (
        "ix_cost_contribution_row_tenant_id",
        "cost_contribution_row",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_contribution_snapshot_tenant_id",
        "cost_contribution_snapshot",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_conversion_basis_revision_tenant_id",
        "cost_conversion_basis_revision",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_correction_basis_tenant_id",
        "cost_correction_basis",
        ("tenant_id",),
        False,
    ),
    ("ix_cost_generation_tenant_id", "cost_generation", ("tenant_id",), False),
    ("ix_cost_input_manifest_tenant_id", "cost_input_manifest", ("tenant_id",), False),
    (
        "ix_cost_inventory_generation_tenant_id",
        "cost_inventory_generation",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_inventory_member_tenant_id",
        "cost_inventory_member",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_inventory_ownership_part_tenant_id",
        "cost_inventory_ownership_part",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_inventory_publication_tenant_id",
        "cost_inventory_publication",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_inventory_review_tenant_id",
        "cost_inventory_review",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_inventory_row_inventory_basis_member_id",
        "cost_inventory_row",
        ("inventory_basis_member_id",),
        False,
    ),
    (
        "ix_cost_inventory_row_owner_party_id",
        "cost_inventory_row",
        ("owner_party_id",),
        False,
    ),
    ("ix_cost_inventory_row_tenant_id", "cost_inventory_row", ("tenant_id",), False),
    (
        "ix_cost_inventory_snapshot_tenant_id",
        "cost_inventory_snapshot",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_manifest_attribution_tenant_id",
        "cost_manifest_attribution",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_manifest_component_tenant_id",
        "cost_manifest_component",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_manifest_correction_tenant_id",
        "cost_manifest_correction",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_manifest_receipt_tenant_id",
        "cost_manifest_receipt",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_manifest_replacement_tenant_id",
        "cost_manifest_replacement",
        ("tenant_id",),
        False,
    ),
    ("ix_cost_movement_basis_tenant_id", "cost_movement_basis", ("tenant_id",), False),
    ("ix_cost_opening_basis_tenant_id", "cost_opening_basis", ("tenant_id",), False),
    (
        "ix_cost_ownership_revision_tenant_id",
        "cost_ownership_revision",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_policy_revision_tenant_id",
        "cost_policy_revision",
        ("tenant_id",),
        False,
    ),
    ("ix_cost_publication_tenant_id", "cost_publication", ("tenant_id",), False),
    ("ix_cost_receipt_basis_tenant_id", "cost_receipt_basis", ("tenant_id",), False),
    (
        "ix_cost_revenue_match_basis_tenant_id",
        "cost_revenue_match_basis",
        ("tenant_id",),
        False,
    ),
    ("ix_cost_scope_review_tenant_id", "cost_scope_review", ("tenant_id",), False),
    (
        "ix_cost_scope_review_category_tenant_id",
        "cost_scope_review_category",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_selling_attribution_part_document_line_id",
        "cost_selling_attribution_part",
        ("document_line_id",),
        False,
    ),
    (
        "ix_cost_selling_attribution_part_tenant_id",
        "cost_selling_attribution_part",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_selling_review_category_tenant_id",
        "cost_selling_review_category",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_selling_review_member_tenant_id",
        "cost_selling_review_member",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_valuation_assessment_part_tenant_id",
        "cost_valuation_assessment_part",
        ("tenant_id",),
        False,
    ),
    (
        "ix_cost_valuation_assessment_revision_tenant_id",
        "cost_valuation_assessment_revision",
        ("tenant_id",),
        False,
    ),
    ("ix_document_party_id", "document", ("party_id",), False),
    ("ix_document_payment_term_id", "document", ("payment_term_id",), False),
    ("ix_document_ship_to_party_id", "document", ("ship_to_party_id",), False),
    ("ix_document_source_record_id", "document", ("source_record_id",), False),
    (
        "ix_document_line_billed_document_line_id",
        "document_line",
        ("billed_document_line_id",),
        False,
    ),
    ("ix_document_line_document_id", "document_line", ("document_id",), False),
    ("ix_document_line_item_id", "document_line", ("item_id",), False),
    (
        "ix_document_line_price_list_entry_id",
        "document_line",
        ("price_list_entry_id",),
        False,
    ),
    ("ix_fact_interpretation_rule_id", "fact", ("interpretation_rule_id",), False),
    ("ix_fact_source_record_id", "fact", ("source_record_id",), False),
    (
        "ix_finance_target_mapping_revision_action_id",
        "finance_target_mapping_revision",
        ("action_id",),
        False,
    ),
    (
        "ix_handling_unit_source_record_id",
        "handling_unit",
        ("source_record_id",),
        False,
    ),
    ("ix_import_job_source_record_id", "import_job", ("source_record_id",), False),
    (
        "ix_interpretation_outcome_import_job_id",
        "interpretation_outcome",
        ("import_job_id",),
        False,
    ),
    (
        "ix_interpretation_outcome_source_record_id",
        "interpretation_outcome",
        ("source_record_id",),
        False,
    ),
    (
        "ix_interpretation_record_reference_outcome_id",
        "interpretation_record_reference",
        ("outcome_id",),
        False,
    ),
    ("ix_interpretation_rule_gap_id", "interpretation_rule", ("gap_id",), False),
    (
        "ix_invitation_delivery_invitation_id",
        "invitation_delivery",
        ("invitation_id",),
        False,
    ),
    ("ix_item_default_location_id", "item", ("default_location_id",), False),
    ("ix_item_source_record_id", "item", ("source_record_id",), False),
    ("ix_ledger_entry_account_id", "ledger_entry", ("account_id",), False),
    ("ix_ledger_entry_document_id", "ledger_entry", ("document_id",), False),
    ("ix_ledger_entry_party_id", "ledger_entry", ("party_id",), False),
    ("ix_ledger_entry_source_record_id", "ledger_entry", ("source_record_id",), False),
    ("ix_location_parent_location_id", "location", ("parent_location_id",), False),
    ("ix_location_source_record_id", "location", ("source_record_id",), False),
    ("ix_lot_item_id", "lot", ("item_id",), False),
    ("ix_lot_source_record_id", "lot", ("source_record_id",), False),
    ("ix_movement_commitment_id", "movement", ("commitment_id",), False),
    ("ix_movement_from_location_id", "movement", ("from_location_id",), False),
    ("ix_movement_handling_unit_id", "movement", ("handling_unit_id",), False),
    ("ix_movement_item_id", "movement", ("item_id",), False),
    ("ix_movement_lot_id", "movement", ("lot_id",), False),
    ("ix_movement_resolves_movement_id", "movement", ("resolves_movement_id",), False),
    (
        "ix_movement_return_announcement_id",
        "movement",
        ("return_announcement_id",),
        False,
    ),
    ("ix_movement_serial_unit_id", "movement", ("serial_unit_id",), False),
    ("ix_movement_shipment_package_id", "movement", ("shipment_package_id",), False),
    ("ix_movement_source_record_id", "movement", ("source_record_id",), False),
    ("ix_movement_to_location_id", "movement", ("to_location_id",), False),
    (
        "ix_movement_correction_compensating_movement_id",
        "movement_correction",
        ("compensating_movement_id",),
        False,
    ),
    (
        "ix_movement_correction_original_movement_id",
        "movement_correction",
        ("original_movement_id",),
        False,
    ),
    (
        "ix_movement_correction_replacement_movement_id",
        "movement_correction",
        ("replacement_movement_id",),
        False,
    ),
    ("ix_opening_scope_party_id", "opening_scope", ("party_id",), False),
    ("ix_party_payment_term_id", "party", ("payment_term_id",), False),
    ("ix_party_source_record_id", "party", ("source_record_id",), False),
    ("ix_party_group_source_record_id", "party_group", ("source_record_id",), False),
    (
        "ix_party_group_member_party_group_id",
        "party_group_member",
        ("party_group_id",),
        False,
    ),
    ("ix_party_group_member_party_id", "party_group_member", ("party_id",), False),
    (
        "ix_party_group_price_list_party_group_id",
        "party_group_price_list",
        ("party_group_id",),
        False,
    ),
    (
        "ix_party_group_price_list_price_list_id",
        "party_group_price_list",
        ("price_list_id",),
        False,
    ),
    ("ix_party_hold_party_id", "party_hold", ("party_id",), False),
    ("ix_party_price_list_party_id", "party_price_list", ("party_id",), False),
    (
        "ix_party_price_list_price_list_id",
        "party_price_list",
        ("price_list_id",),
        False,
    ),
    (
        "ix_party_role_default_location_id",
        "party_role",
        ("default_location_id",),
        False,
    ),
    ("ix_party_role_party_id", "party_role", ("party_id",), False),
    ("ix_payment_term_source_record_id", "payment_term", ("source_record_id",), False),
    ("ix_price_list_source_record_id", "price_list", ("source_record_id",), False),
    ("ix_price_list_entry_item_id", "price_list_entry", ("item_id",), False),
    (
        "ix_price_list_entry_price_list_id",
        "price_list_entry",
        ("price_list_id",),
        False,
    ),
    (
        "ix_price_list_entry_source_record_id",
        "price_list_entry",
        ("source_record_id",),
        False,
    ),
    ("ix_reality_gap_entry_gap_id", "reality_gap_entry", ("gap_id",), False),
    ("ix_reservation_commitment_id", "reservation", ("commitment_id",), False),
    ("ix_reservation_handling_unit_id", "reservation", ("handling_unit_id",), False),
    ("ix_reservation_item_id", "reservation", ("item_id",), False),
    ("ix_reservation_location_id", "reservation", ("location_id",), False),
    ("ix_reservation_lot_id", "reservation", ("lot_id",), False),
    ("ix_reservation_serial_unit_id", "reservation", ("serial_unit_id",), False),
    (
        "ix_return_announcement_commitment_id",
        "return_announcement",
        ("commitment_id",),
        False,
    ),
    (
        "ix_return_announcement_source_record_id",
        "return_announcement",
        ("source_record_id",),
        False,
    ),
    (
        "ix_rule_interpretation_outcome_fact_id",
        "rule_interpretation_outcome",
        ("fact_id",),
        False,
    ),
    (
        "ix_rule_interpretation_outcome_rule_id",
        "rule_interpretation_outcome",
        ("rule_id",),
        False,
    ),
    (
        "ix_rule_interpretation_outcome_source_record_id",
        "rule_interpretation_outcome",
        ("source_record_id",),
        False,
    ),
    ("ix_secret_audit_event_secret_id", "secret_audit_event", ("secret_id",), False),
    ("ix_serial_unit_item_id", "serial_unit", ("item_id",), False),
    ("ix_serial_unit_lot_id", "serial_unit", ("lot_id",), False),
    ("ix_serial_unit_source_record_id", "serial_unit", ("source_record_id",), False),
    (
        "ix_settlement_allocation_invoice_ledger_entry_id",
        "settlement_allocation",
        ("invoice_ledger_entry_id",),
        False,
    ),
    (
        "ix_settlement_allocation_payment_ledger_entry_id",
        "settlement_allocation",
        ("payment_ledger_entry_id",),
        False,
    ),
    ("ix_shipment_counterparty_id", "shipment", ("counterparty_id",), False),
    ("ix_shipment_source_record_id", "shipment", ("source_record_id",), False),
    ("ix_shipment_event_shipment_id", "shipment_event", ("shipment_id",), False),
    (
        "ix_shipment_event_shipment_package_id",
        "shipment_event",
        ("shipment_package_id",),
        False,
    ),
    (
        "ix_shipment_event_source_record_id",
        "shipment_event",
        ("source_record_id",),
        False,
    ),
    (
        "ix_shipment_event_supersession_replacement_event_id",
        "shipment_event_supersession",
        ("replacement_event_id",),
        False,
    ),
    (
        "ix_shipment_event_supersession_source_record_id",
        "shipment_event_supersession",
        ("source_record_id",),
        False,
    ),
    (
        "ix_shipment_event_supersession_superseded_event_id",
        "shipment_event_supersession",
        ("superseded_event_id",),
        False,
    ),
    ("ix_shipment_package_shipment_id", "shipment_package", ("shipment_id",), False),
    (
        "ix_shipment_package_source_record_id",
        "shipment_package",
        ("source_record_id",),
        False,
    ),
    (
        "ix_source_capability_source_system_id",
        "source_capability",
        ("source_system_id",),
        False,
    ),
    (
        "ix_source_classification_mapping_revision_action_id",
        "source_classification_mapping_revision",
        ("action_id",),
        False,
    ),
    (
        "ix_source_record_source_artifact_id",
        "source_record",
        ("source_artifact_id",),
        False,
    ),
    (
        "ix_source_record_supersedes_source_record_id",
        "source_record",
        ("supersedes_source_record_id",),
        False,
    ),
    (
        "ix_source_stream_current_source_record_id",
        "source_stream",
        ("current_source_record_id",),
        False,
    ),
)

INDEX_CREATES: tuple[tuple[str, str, tuple[str, ...], bool], ...] = (
    (
        "ix_ai_settings_api_key_secret_id",
        "ai_settings",
        ("tenant_id", "api_key_secret_id"),
        False,
    ),
    ("ix_analysis_request_run_id", "analysis_request", ("tenant_id", "run_id"), False),
    (
        "ix_business_event_action_id",
        "business_event",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_business_event_causation_id",
        "business_event",
        ("tenant_id", "causation_id"),
        False,
    ),
    (
        "ix_business_event_source_record_id",
        "business_event",
        ("tenant_id", "source_record_id"),
        False,
    ),
    ("ix_chat_message_session_id", "chat_message", ("tenant_id", "session_id"), False),
    ("ix_commitment_document_id", "commitment", ("tenant_id", "document_id"), False),
    (
        "ix_commitment_from_party_id",
        "commitment",
        ("tenant_id", "from_party_id"),
        False,
    ),
    ("ix_commitment_item_id", "commitment", ("tenant_id", "item_id"), False),
    ("ix_commitment_location_id", "commitment", ("tenant_id", "location_id"), False),
    ("ix_commitment_to_party_id", "commitment", ("tenant_id", "to_party_id"), False),
    (
        "ix_commitment_hold_commitment_id",
        "commitment_hold",
        ("tenant_id", "commitment_id"),
        False,
    ),
    (
        "ix_commitment_revision_commitment_id",
        "commitment_revision",
        ("tenant_id", "commitment_id"),
        False,
    ),
    (
        "ix_commitment_revision_source_record_id",
        "commitment_revision",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_component_assignment_part_cost_center_reference_id__a1b6a907",
        "component_assignment_part",
        ("tenant_id", "cost_center_reference_id", "reference_kind"),
        False,
    ),
    (
        "ix_component_assignment_revision_action_id",
        "component_assignment_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_component_assignment_revision_case_reference_id_case_kind",
        "component_assignment_revision",
        ("tenant_id", "case_reference_id", "case_kind"),
        False,
    ),
    (
        "ix_component_assignment_revision_group_reference_id_group_kind",
        "component_assignment_revision",
        ("tenant_id", "group_reference_id", "group_kind"),
        False,
    ),
    (
        "ix_cost_attribution_part_conversion_basis_revision_id",
        "cost_attribution_part",
        ("tenant_id", "conversion_basis_revision_id"),
        False,
    ),
    (
        "ix_cost_attribution_part_receipt_basis_id",
        "cost_attribution_part",
        ("tenant_id", "receipt_basis_id"),
        False,
    ),
    (
        "ix_cost_attribution_revision_action_id",
        "cost_attribution_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_attribution_revision_introduced_event_id",
        "cost_attribution_revision",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_captured_basis_census_id",
        "cost_captured_basis",
        ("tenant_id", "census_id"),
        False,
    ),
    (
        "ix_cost_captured_contribution_basis_document_line_id",
        "cost_captured_contribution_basis",
        ("tenant_id", "document_line_id"),
        False,
    ),
    (
        "ix_cost_captured_contribution_basis_review_id",
        "cost_captured_contribution_basis",
        ("tenant_id", "review_id"),
        False,
    ),
    (
        "ix_cost_captured_inventory_basis_item_id",
        "cost_captured_inventory_basis",
        ("tenant_id", "item_id"),
        False,
    ),
    (
        "ix_cost_captured_inventory_basis_review_id",
        "cost_captured_inventory_basis",
        ("tenant_id", "review_id"),
        False,
    ),
    (
        "ix_cost_commercial_direct_part_attribution_revision_id",
        "cost_commercial_direct_part",
        ("tenant_id", "attribution_revision_id"),
        False,
    ),
    (
        "ix_cost_commercial_inventory_part_entry_movement_basis_id",
        "cost_commercial_inventory_part",
        ("tenant_id", "entry_movement_basis_id"),
        False,
    ),
    (
        "ix_cost_commercial_inventory_part_inventory_member_id",
        "cost_commercial_inventory_part",
        ("tenant_id", "inventory_member_id"),
        False,
    ),
    (
        "ix_cost_commercial_inventory_part_original_issue_member_id",
        "cost_commercial_inventory_part",
        ("tenant_id", "original_issue_member_id"),
        False,
    ),
    (
        "ix_cost_commercial_inventory_part_receipt_movement_basis_id",
        "cost_commercial_inventory_part",
        ("tenant_id", "receipt_movement_basis_id"),
        False,
    ),
    (
        "ix_cost_commercial_match_revision_action_id",
        "cost_commercial_match_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_commercial_match_revision_introduced_event_id",
        "cost_commercial_match_revision",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_commercial_match_revision_order_line_id",
        "cost_commercial_match_revision",
        ("tenant_id", "order_line_id"),
        False,
    ),
    (
        "ix_cost_company_census_document_document_id",
        "cost_company_census_document",
        ("tenant_id", "document_id"),
        False,
    ),
    (
        "ix_cost_company_census_line_census_id_document_member_id",
        "cost_company_census_line",
        ("tenant_id", "census_id", "document_member_id"),
        False,
    ),
    (
        "ix_cost_company_census_line_document_line_id",
        "cost_company_census_line",
        ("tenant_id", "document_line_id"),
        False,
    ),
    (
        "ix_cost_company_census_movement_movement_id",
        "cost_company_census_movement",
        ("tenant_id", "movement_id"),
        False,
    ),
    (
        "ix_cost_company_census_source_interpretation_outcome_id",
        "cost_company_census_source",
        ("tenant_id", "interpretation_outcome_id"),
        False,
    ),
    (
        "ix_cost_company_census_source_source_record_id",
        "cost_company_census_source",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_cost_company_contribution_input_census_line_id",
        "cost_company_contribution_input",
        ("tenant_id", "census_line_id"),
        False,
    ),
    (
        "ix_cost_company_contribution_input_inventory_review_id",
        "cost_company_contribution_input",
        ("tenant_id", "inventory_review_id"),
        False,
    ),
    (
        "ix_cost_company_contribution_input_review_id",
        "cost_company_contribution_input",
        ("tenant_id", "review_id"),
        False,
    ),
    (
        "ix_cost_company_contribution_result_contribution_generation_id",
        "cost_company_contribution_result",
        ("tenant_id", "contribution_generation_id"),
        False,
    ),
    (
        "ix_cost_company_contribution_result_contribution_input_id",
        "cost_company_contribution_result",
        ("tenant_id", "contribution_input_id"),
        False,
    ),
    (
        "ix_cost_company_contribution_result_review_id",
        "cost_company_contribution_result",
        ("tenant_id", "review_id"),
        False,
    ),
    (
        "ix_cost_company_inventory_input_item_id",
        "cost_company_inventory_input",
        ("tenant_id", "item_id"),
        False,
    ),
    (
        "ix_cost_company_inventory_input_review_id",
        "cost_company_inventory_input",
        ("tenant_id", "review_id"),
        False,
    ),
    (
        "ix_cost_company_inventory_result_inventory_generation_id",
        "cost_company_inventory_result",
        ("tenant_id", "inventory_generation_id"),
        False,
    ),
    (
        "ix_cost_company_inventory_result_inventory_input_id",
        "cost_company_inventory_result",
        ("tenant_id", "inventory_input_id"),
        False,
    ),
    (
        "ix_cost_company_manifest_census_id",
        "cost_company_manifest",
        ("tenant_id", "census_id"),
        False,
    ),
    (
        "ix_cost_company_publication_scope_key_generation_id",
        "cost_company_publication",
        ("tenant_id", "scope_key", "generation_id"),
        False,
    ),
    (
        "ix_cost_component_basis_interpretation_outcome_id",
        "cost_component_basis",
        ("tenant_id", "interpretation_outcome_id"),
        False,
    ),
    (
        "ix_cost_component_basis_introduced_event_id",
        "cost_component_basis",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_component_replacement_action_id",
        "cost_component_replacement",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_component_replacement_introduced_event_id",
        "cost_component_replacement",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_contribution_review_action_id",
        "cost_contribution_review",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_contribution_review_introduced_event_id",
        "cost_contribution_review",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_contribution_review_inventory_member_id",
        "cost_contribution_review",
        ("tenant_id", "inventory_member_id"),
        False,
    ),
    (
        "ix_cost_contribution_row_contribution_basis_member_id",
        "cost_contribution_row",
        ("tenant_id", "contribution_basis_member_id"),
        False,
    ),
    (
        "ix_cost_contribution_snapshot_review_id",
        "cost_contribution_snapshot",
        ("tenant_id", "review_id"),
        False,
    ),
    (
        "ix_cost_conversion_basis_revision_action_id",
        "cost_conversion_basis_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_conversion_basis_revision_evidence_source_record_id",
        "cost_conversion_basis_revision",
        ("tenant_id", "evidence_source_record_id"),
        False,
    ),
    (
        "ix_cost_conversion_basis_revision_introduced_event_id",
        "cost_conversion_basis_revision",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_correction_basis_introduced_event_id",
        "cost_correction_basis",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_inventory_generation_assessment_revision_id",
        "cost_inventory_generation",
        ("tenant_id", "assessment_revision_id"),
        False,
    ),
    (
        "ix_cost_inventory_member_movement_basis_id",
        "cost_inventory_member",
        ("tenant_id", "movement_basis_id"),
        False,
    ),
    (
        "ix_cost_inventory_member_ownership_revision_id",
        "cost_inventory_member",
        ("tenant_id", "ownership_revision_id"),
        False,
    ),
    (
        "ix_cost_inventory_member_receipt_manifest_id",
        "cost_inventory_member",
        ("tenant_id", "receipt_manifest_id"),
        False,
    ),
    (
        "ix_cost_inventory_ownership_part_evidence_source_record_id",
        "cost_inventory_ownership_part",
        ("tenant_id", "evidence_source_record_id"),
        False,
    ),
    (
        "ix_cost_inventory_ownership_part_movement_basis_id",
        "cost_inventory_ownership_part",
        ("tenant_id", "movement_basis_id"),
        False,
    ),
    (
        "ix_cost_inventory_ownership_part_owner_party_id",
        "cost_inventory_ownership_part",
        ("tenant_id", "owner_party_id"),
        False,
    ),
    (
        "ix_cost_inventory_publication_review_id_generation_id",
        "cost_inventory_publication",
        ("tenant_id", "review_id", "generation_id"),
        False,
    ),
    (
        "ix_cost_inventory_review_action_id",
        "cost_inventory_review",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_inventory_review_introduced_event_id",
        "cost_inventory_review",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_inventory_row_inventory_basis_member_id",
        "cost_inventory_row",
        ("tenant_id", "inventory_basis_member_id"),
        False,
    ),
    (
        "ix_cost_inventory_row_owner_party_id",
        "cost_inventory_row",
        ("tenant_id", "owner_party_id"),
        False,
    ),
    (
        "ix_cost_manifest_attribution_attribution_revision_id",
        "cost_manifest_attribution",
        ("tenant_id", "attribution_revision_id"),
        False,
    ),
    (
        "ix_cost_manifest_component_component_basis_id",
        "cost_manifest_component",
        ("tenant_id", "component_basis_id"),
        False,
    ),
    (
        "ix_cost_manifest_correction_correction_basis_id",
        "cost_manifest_correction",
        ("tenant_id", "correction_basis_id"),
        False,
    ),
    (
        "ix_cost_manifest_receipt_receipt_basis_id",
        "cost_manifest_receipt",
        ("tenant_id", "receipt_basis_id"),
        False,
    ),
    (
        "ix_cost_manifest_replacement_replacement_id",
        "cost_manifest_replacement",
        ("tenant_id", "replacement_id"),
        False,
    ),
    (
        "ix_cost_movement_basis_introduced_event_id",
        "cost_movement_basis",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_movement_basis_movement_event_id",
        "cost_movement_basis",
        ("tenant_id", "movement_event_id"),
        False,
    ),
    (
        "ix_cost_opening_basis_action_id",
        "cost_opening_basis",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_opening_basis_evidence_source_record_id",
        "cost_opening_basis",
        ("tenant_id", "evidence_source_record_id"),
        False,
    ),
    (
        "ix_cost_opening_basis_introduced_event_id",
        "cost_opening_basis",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_opening_basis_owner_party_id",
        "cost_opening_basis",
        ("tenant_id", "owner_party_id"),
        False,
    ),
    (
        "ix_cost_ownership_revision_action_id",
        "cost_ownership_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_ownership_revision_evidence_source_record_id",
        "cost_ownership_revision",
        ("tenant_id", "evidence_source_record_id"),
        False,
    ),
    (
        "ix_cost_ownership_revision_introduced_event_id",
        "cost_ownership_revision",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_ownership_revision_owner_party_id",
        "cost_ownership_revision",
        ("tenant_id", "owner_party_id"),
        False,
    ),
    (
        "ix_cost_policy_revision_action_id",
        "cost_policy_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_policy_revision_introduced_event_id",
        "cost_policy_revision",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_policy_revision_owner_party_id",
        "cost_policy_revision",
        ("tenant_id", "owner_party_id"),
        False,
    ),
    (
        "ix_cost_publication_scope_key_generation_id",
        "cost_publication",
        ("tenant_id", "scope_key", "generation_id"),
        False,
    ),
    (
        "ix_cost_receipt_basis_introduced_event_id",
        "cost_receipt_basis",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_revenue_match_basis_customer_id",
        "cost_revenue_match_basis",
        ("tenant_id", "customer_id"),
        False,
    ),
    (
        "ix_cost_revenue_match_basis_introduced_event_id",
        "cost_revenue_match_basis",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_revenue_match_basis_item_id",
        "cost_revenue_match_basis",
        ("tenant_id", "item_id"),
        False,
    ),
    (
        "ix_cost_revenue_match_basis_order_line_id",
        "cost_revenue_match_basis",
        ("tenant_id", "order_line_id"),
        False,
    ),
    (
        "ix_cost_scope_review_action_id",
        "cost_scope_review",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_scope_review_introduced_event_id",
        "cost_scope_review",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_cost_scope_review_manifest_id",
        "cost_scope_review",
        ("tenant_id", "manifest_id"),
        False,
    ),
    (
        "ix_cost_selling_attribution_part_conversion_basis_revision_id",
        "cost_selling_attribution_part",
        ("tenant_id", "conversion_basis_revision_id"),
        False,
    ),
    (
        "ix_cost_selling_attribution_part_document_line_id",
        "cost_selling_attribution_part",
        ("tenant_id", "document_line_id"),
        False,
    ),
    (
        "ix_cost_selling_review_member_part_id",
        "cost_selling_review_member",
        ("tenant_id", "part_id"),
        False,
    ),
    (
        "ix_cost_valuation_assessment_part_evidence_source_record_id",
        "cost_valuation_assessment_part",
        ("tenant_id", "evidence_source_record_id"),
        False,
    ),
    (
        "ix_cost_valuation_assessment_part_inventory_member_id",
        "cost_valuation_assessment_part",
        ("tenant_id", "inventory_member_id"),
        False,
    ),
    (
        "ix_cost_valuation_assessment_revision_action_id",
        "cost_valuation_assessment_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_cost_valuation_assessment_revision_introduced_event_id",
        "cost_valuation_assessment_revision",
        ("tenant_id", "introduced_event_id"),
        False,
    ),
    (
        "ix_demo_data_connection_current_schedule_id",
        "demo_data_connection",
        ("tenant_id", "current_schedule_id"),
        False,
    ),
    (
        "ix_demo_data_connection_settlement_schedule_id",
        "demo_data_connection",
        ("tenant_id", "settlement_schedule_id"),
        False,
    ),
    (
        "ix_demo_data_connection_source_system_id",
        "demo_data_connection",
        ("tenant_id", "source_system_id"),
        False,
    ),
    ("ix_document_party_id", "document", ("tenant_id", "party_id"), False),
    (
        "ix_document_payment_term_id",
        "document",
        ("tenant_id", "payment_term_id"),
        False,
    ),
    (
        "ix_document_ship_to_party_id",
        "document",
        ("tenant_id", "ship_to_party_id"),
        False,
    ),
    (
        "ix_document_line_billed_document_line_id",
        "document_line",
        ("tenant_id", "billed_document_line_id"),
        False,
    ),
    ("ix_document_line_item_id", "document_line", ("tenant_id", "item_id"), False),
    (
        "ix_document_line_price_list_entry_id",
        "document_line",
        ("tenant_id", "price_list_entry_id"),
        False,
    ),
    (
        "ix_fact_interpretation_rule_id",
        "fact",
        ("tenant_id", "interpretation_rule_id"),
        False,
    ),
    ("ix_fact_source_record_id", "fact", ("tenant_id", "source_record_id"), False),
    (
        "ix_finance_role_destination_account_id",
        "finance_role_destination",
        ("tenant_id", "account_id"),
        False,
    ),
    (
        "ix_finance_target_mapping_revision_action_id",
        "finance_target_mapping_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_finance_target_mapping_revision_case_reference_id_case_kind",
        "finance_target_mapping_revision",
        ("tenant_id", "case_reference_id", "case_kind"),
        False,
    ),
    (
        "ix_finance_target_mapping_revision_group_reference_id__40a11f0a",
        "finance_target_mapping_revision",
        ("tenant_id", "group_reference_id", "group_kind"),
        False,
    ),
    (
        "ix_finance_target_mapping_revision_local_account_id",
        "finance_target_mapping_revision",
        ("tenant_id", "local_account_id"),
        False,
    ),
    (
        "ix_finance_target_mapping_revision_replaces_id",
        "finance_target_mapping_revision",
        ("tenant_id", "replaces_id"),
        False,
    ),
    (
        "ix_finance_target_mapping_revision_target_id_external__1030a826",
        "finance_target_mapping_revision",
        ("tenant_id", "target_id", "external_account_id", "account_kind"),
        False,
    ),
    (
        "ix_finance_target_mapping_revision_target_id_external__b45da77a",
        "finance_target_mapping_revision",
        ("tenant_id", "target_id", "external_tax_code_id", "tax_kind"),
        False,
    ),
    (
        "ix_handling_unit_source_record_id",
        "handling_unit",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_interpretation_outcome_source_record_id",
        "interpretation_outcome",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_interpretation_rule_gap_id",
        "interpretation_rule",
        ("tenant_id", "gap_id"),
        False,
    ),
    (
        "ix_item_default_location_id",
        "item",
        ("tenant_id", "default_location_id"),
        False,
    ),
    ("ix_item_source_record_id", "item", ("tenant_id", "source_record_id"), False),
    ("ix_ledger_entry_account_id", "ledger_entry", ("tenant_id", "account_id"), False),
    (
        "ix_ledger_entry_document_id",
        "ledger_entry",
        ("tenant_id", "document_id"),
        False,
    ),
    ("ix_ledger_entry_party_id", "ledger_entry", ("tenant_id", "party_id"), False),
    (
        "ix_ledger_entry_source_record_id",
        "ledger_entry",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_location_parent_location_id",
        "location",
        ("tenant_id", "parent_location_id"),
        False,
    ),
    (
        "ix_location_source_record_id",
        "location",
        ("tenant_id", "source_record_id"),
        False,
    ),
    ("ix_lot_source_record_id", "lot", ("tenant_id", "source_record_id"), False),
    ("ix_movement_commitment_id", "movement", ("tenant_id", "commitment_id"), False),
    (
        "ix_movement_from_location_id",
        "movement",
        ("tenant_id", "from_location_id"),
        False,
    ),
    (
        "ix_movement_handling_unit_id",
        "movement",
        ("tenant_id", "handling_unit_id"),
        False,
    ),
    ("ix_movement_lot_id", "movement", ("tenant_id", "lot_id"), False),
    (
        "ix_movement_resolves_movement_id",
        "movement",
        ("tenant_id", "resolves_movement_id"),
        False,
    ),
    (
        "ix_movement_return_announcement_id",
        "movement",
        ("tenant_id", "return_announcement_id"),
        False,
    ),
    ("ix_movement_serial_unit_id", "movement", ("tenant_id", "serial_unit_id"), False),
    (
        "ix_movement_shipment_package_id",
        "movement",
        ("tenant_id", "shipment_package_id"),
        False,
    ),
    (
        "ix_movement_source_record_id",
        "movement",
        ("tenant_id", "source_record_id"),
        False,
    ),
    ("ix_movement_to_location_id", "movement", ("tenant_id", "to_location_id"), False),
    (
        "ix_movement_correction_compensating_movement_id",
        "movement_correction",
        ("tenant_id", "compensating_movement_id"),
        False,
    ),
    (
        "ix_movement_correction_original_movement_id",
        "movement_correction",
        ("tenant_id", "original_movement_id"),
        False,
    ),
    (
        "ix_movement_correction_replacement_movement_id",
        "movement_correction",
        ("tenant_id", "replacement_movement_id"),
        False,
    ),
    (
        "ix_opening_item_detail_document_id",
        "opening_item_detail",
        ("tenant_id", "document_id"),
        False,
    ),
    ("ix_opening_scope_party_id", "opening_scope", ("tenant_id", "party_id"), False),
    ("ix_party_payment_term_id", "party", ("tenant_id", "payment_term_id"), False),
    ("ix_party_source_record_id", "party", ("tenant_id", "source_record_id"), False),
    (
        "ix_party_group_source_record_id",
        "party_group",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_party_group_member_party_id",
        "party_group_member",
        ("tenant_id", "party_id"),
        False,
    ),
    (
        "ix_party_group_price_list_price_list_id",
        "party_group_price_list",
        ("tenant_id", "price_list_id"),
        False,
    ),
    ("ix_party_hold_party_id", "party_hold", ("tenant_id", "party_id"), False),
    (
        "ix_party_price_list_price_list_id",
        "party_price_list",
        ("tenant_id", "price_list_id"),
        False,
    ),
    (
        "ix_party_role_default_location_id",
        "party_role",
        ("tenant_id", "default_location_id"),
        False,
    ),
    (
        "ix_payment_term_source_record_id",
        "payment_term",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_playground_step_proposal_id",
        "playground_step",
        ("tenant_id", "proposal_id"),
        False,
    ),
    ("ix_playground_step_run_id", "playground_step", ("tenant_id", "run_id"), False),
    (
        "ix_price_list_source_record_id",
        "price_list",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_price_list_entry_item_id",
        "price_list_entry",
        ("tenant_id", "item_id"),
        False,
    ),
    (
        "ix_price_list_entry_source_record_id",
        "price_list_entry",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_reality_gap_entry_gap_id",
        "reality_gap_entry",
        ("tenant_id", "gap_id"),
        False,
    ),
    (
        "ix_reservation_commitment_id",
        "reservation",
        ("tenant_id", "commitment_id"),
        False,
    ),
    (
        "ix_reservation_handling_unit_id",
        "reservation",
        ("tenant_id", "handling_unit_id"),
        False,
    ),
    ("ix_reservation_item_id", "reservation", ("tenant_id", "item_id"), False),
    ("ix_reservation_location_id", "reservation", ("tenant_id", "location_id"), False),
    ("ix_reservation_lot_id", "reservation", ("tenant_id", "lot_id"), False),
    (
        "ix_reservation_serial_unit_id",
        "reservation",
        ("tenant_id", "serial_unit_id"),
        False,
    ),
    (
        "ix_return_announcement_commitment_id",
        "return_announcement",
        ("tenant_id", "commitment_id"),
        False,
    ),
    (
        "ix_return_announcement_source_record_id",
        "return_announcement",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_rule_interpretation_outcome_fact_id",
        "rule_interpretation_outcome",
        ("tenant_id", "fact_id"),
        False,
    ),
    (
        "ix_rule_interpretation_outcome_source_record_id",
        "rule_interpretation_outcome",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_secret_audit_event_secret_id",
        "secret_audit_event",
        ("tenant_id", "secret_id"),
        False,
    ),
    ("ix_serial_unit_lot_id", "serial_unit", ("tenant_id", "lot_id"), False),
    (
        "ix_serial_unit_source_record_id",
        "serial_unit",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_settlement_allocation_invoice_ledger_entry_id",
        "settlement_allocation",
        ("tenant_id", "invoice_ledger_entry_id"),
        False,
    ),
    (
        "ix_settlement_allocation_payment_ledger_entry_id",
        "settlement_allocation",
        ("tenant_id", "payment_ledger_entry_id"),
        False,
    ),
    (
        "ix_shipment_source_record_id",
        "shipment",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_shipment_event_source_record_id",
        "shipment_event",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_shipment_event_supersession_replacement_event_id",
        "shipment_event_supersession",
        ("tenant_id", "replacement_event_id"),
        False,
    ),
    (
        "ix_shipment_event_supersession_source_record_id",
        "shipment_event_supersession",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_shipment_package_source_record_id",
        "shipment_package",
        ("tenant_id", "source_record_id"),
        False,
    ),
    (
        "ix_source_classification_mapping_revision_action_id",
        "source_classification_mapping_revision",
        ("tenant_id", "action_id"),
        False,
    ),
    (
        "ix_source_classification_mapping_revision_reference_id_e962fcbd",
        "source_classification_mapping_revision",
        ("tenant_id", "reference_id", "field_kind"),
        False,
    ),
    (
        "ix_source_classification_mapping_revision_replaces_id",
        "source_classification_mapping_revision",
        ("tenant_id", "replaces_id"),
        False,
    ),
    (
        "ix_source_record_source_artifact_id",
        "source_record",
        ("tenant_id", "source_artifact_id"),
        False,
    ),
    (
        "ix_source_record_supersedes_source_record_id",
        "source_record",
        ("tenant_id", "supersedes_source_record_id"),
        False,
    ),
    (
        "ix_source_stream_current_source_record_id",
        "source_stream",
        ("tenant_id", "current_source_record_id"),
        False,
    ),
)


def _constraint_name(table: str, columns: tuple[str, ...], target: str) -> str | None:
    """What this database calls that reference, or None if it does not have it."""
    row = (
        op.get_bind()
        .exec_driver_sql(
            """
        SELECT con.conname
          FROM pg_constraint con
          JOIN pg_class child ON child.oid = con.conrelid
          JOIN pg_class parent ON parent.oid = con.confrelid
         WHERE con.contype = 'f'
           AND child.relname = %s
           AND parent.relname = %s
           AND (
                 SELECT array_agg(a.attname ORDER BY k.ord)
                   FROM unnest(con.conkey) WITH ORDINALITY k(attnum, ord)
                   JOIN pg_attribute a
                     ON a.attrelid = con.conrelid AND a.attnum = k.attnum
               ) = %s::name[]
        """,
            (table, target, list(columns)),
        )
        .first()
    )
    return row[0] if row else None


def upgrade() -> None:
    # Order matters and is global rather than per table: every reference that
    # rests on a key has to be gone before any key moves, because one table's
    # child is another's parent.
    for table, columns, target, _declared, _ondelete in DROPPED:
        name = _constraint_name(table, columns, target)
        if name:
            op.drop_constraint(name, table, type_="foreignkey")
    for name, table, columns, unique in INDEX_DROPS:
        op.execute(f'DROP INDEX IF EXISTS "{name}"')
    for table in SCOPED:
        op.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT "{table}_pkey"')
        op.create_primary_key(f"{table}_pkey", table, ["tenant_id", "id"])
    for table, columns, target, target_columns, ondelete, name in REFERENCES:
        op.create_foreign_key(
            name or None,
            table,
            target,
            list(columns),
            list(target_columns),
            ondelete=ondelete or None,
        )
    for name, table, columns, unique in INDEX_CREATES:
        op.create_index(name, table, list(columns), unique=unique)


def downgrade() -> None:
    """Put the narrower key back, and let PostgreSQL refuse if it no longer fits.

    Going back is only possible while no two companies have drawn the same
    identity, because the old key was `id` alone. Every identity here is random,
    so no database holds such a pair today — and if one ever did, the key below
    would refuse to build rather than quietly lose a row, which is the behaviour
    worth keeping.
    """
    for name, table, columns, unique in reversed(INDEX_CREATES):
        op.execute(f'DROP INDEX IF EXISTS "{name}"')
    for table, columns, target, target_columns, ondelete, name in reversed(REFERENCES):
        existing = _constraint_name(table, columns, target)
        if existing:
            op.drop_constraint(existing, table, type_="foreignkey")
    for table in reversed(SCOPED):
        op.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT "{table}_pkey"')
        op.create_primary_key(f"{table}_pkey", table, ["id"])
    for table, columns, target, declared, ondelete in reversed(DROPPED):
        # Under the name it had. A later revision drops some of these by name
        # and would not find them if PostgreSQL had made one up here.
        op.create_foreign_key(
            declared or None,
            table,
            target,
            list(columns),
            ["id"],
            ondelete=ondelete or None,
        )
    for name, table, columns, unique in reversed(INDEX_DROPS):
        op.create_index(name, table, list(columns), unique=unique)
